capital:
  initial_capital: 100000
  transaction_cost: 0
credentials:
  client_id: 1
  ib_port: 7497
data:
  commodities:
  - GLD
  - GDX
  time_length_days: 180
  time_scale: 1 min
  training_threshold: 3
model:
  fitting_method: OLS
strategy:
  window: 100
  z_threshold: 1
