capital:
  initial_capital: 100000
  transaction_cost: 0.0035
credentials:
  client_id: 1
  ib_port: 7497
data:
  commodities:
  - GLD
  - GDX
  time_length_days: 30
  time_scale: 1 min
  training_threshold: 10
model:
  fitting_method: OLS
strategy:
  window: 10
  z_threshold: 2.5
